# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

IP_NW = "192.168.0.0"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  # Provision Master Nodes
  config.vm.define "devsecops" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubernetes-devsecops"
            vb.memory = 7048
            vb.cpus = 4
        end
        node.vm.hostname = "devsecops"
        node.vm.network :private_network, ip: IP_NW 
        node.vm.network "forwarded_port", guest: 22, host: "#{2710}"

        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"

  end
end

  
